### ISSUE TITLE
In a docker environment catalog:images:remove-unused-files fails

### ISSUE THREAD

**Issue by pabodah** [baldwin-agency/magento2-module-image-cleanup#8]
Hello,

I'm executing the command **bin/magento catalog:images:remove-unused-files** in a docker environment.
The command outputs an error
![image](https://github.com/user-attachments/assets/96039667-558b-46aa-a5dc-f1f51b20841f)
`Searching for unused files:
    0 [>---------------------------]
In File.php line 306:
                                                                               
  FilesystemIterator::__construct(/var/www/html/pub/media/catalog/product/cac  
  he): Failed to open directory: No such file or directory                     
                                                                               

In File.php line 297:
                                                                               
  FilesystemIterator::__construct(/var/www/html/pub/media/catalog/product/cac  
  he): Failed to open directory: No such file or directory `

**Comment by hostep** [comment]
Right, we first need to check if the `product/cache` directory exists, I ran into this myself as well a while ago.

You can quickly fix it by generating that directory manually.

But you can leave this ticket open, I'll add a check to see if that directory exists before trying to do something with it.

Thanks for reporting!

**Comment by hostep** [comment]
Could you try again with version [1.2.4](https://github.com/baldwin-agency/magento2-module-image-cleanup/releases/tag/v1.2.4)? It should be resolved.

Thanks again for reporting this!

**Comment by pabodah** [comment]
Thank you. 
I was able to execute the command now.
